[build]
  command = "npm run build"
  publish = "build"

  [dev]
  cmmand = "vite dev"

  [functions]
  directory = "netlify/functions"

[[_redirects]]
  from = "/*"
  to = "/app.html"
  status = 200
